version: '2'
services:
    jhipsteruaaserverapplication-app:
        image: jhipsteruaaserverapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsteruaaserverapplication-mysql:3306/jhipsteruaaserverapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipsteruaaserverapplication-elasticsearch:9300
    jhipsteruaaserverapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipsteruaaserverapplication-mysql
    jhipsteruaaserverapplication-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipsteruaaserverapplication-elasticsearch
